Draft: v2.1.0
rock-simulation/phobos pull request #364
Opened 2024-06-13 09:05 UTC by hwiedPro

## Description
### Python Module:
- ci:
      - Support for Azure Pipelines
      - Split ci pushes to Failure, Success and Production Branch, so that all pipeline pushes can be reviewed before production
      - Extended Test-protocols in PRs
      - Improve configurability of model_def by hierarchical defaults
      - autogenerated files can be marked as such
      - Results from feature/* branches will be pushed to the corresponding feature/* branch in the target repo, for testing purposes
- scripts:
      - phobos convert: Fix for Scenes/Worlds, Args for mesh type and export config
- core/io:
      - Refactor utils
      - Adaption in defaults.json
      - Several bugfixes in mesh handling
      - Bugfixes for poses
      - Configurability for exports has been extended
      - Enhanced submodel export
      - Bugfixes for import/export
- smurf:
      - Include list of submodels
      - A mesh collision can now be annotated with primitive collisions, during export the user can decide what to export
- general:
      - Several error messages have been improved
      - Minor codestyle improvements
      - Updated ROS templates for ROS2
    
### Blender:
- Only minor bugfixes
- Most bugfixes in Python Module apply here as well
    
### ToDo:
  - [ ] Documentation has to be updated accordingly

## Related Issues/PRs
#363 #352 #357 #354

## Motivation and Context
See Changelog above

## How Has This Been Tested?
- Scripts and Pipeline have been tested in an integrated environment
- [ ] @AlpenAalAlex Would you be so kind to test this at your end?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

2024-06-24 13:47 UTC, AlpenAalAlex requested changes, later dismissed
Left comments on:
[phobos/ci/base_model.py](https://github.com/dfki-ric/phobos/pull/364/commits/6492934febb1115c1314ea740861fbf7d12f4bdf#diff-77065fd661bd806462286202defb07c88ea26d27d13e0503f91be26cad81b4fa):948
[phobos/utils/misc.py](https://github.com/dfki-ric/phobos/pull/364/commits/9db3b92cfd9e3bad96766ac793a8d5a93df0c8f4#diff-ea4e02022d3afe07d40322dc6023219b711f4b0962d4b3a2243b48dda01d4b6f):291

Everything else looks good 👍

2024-06-24 13:47 UTC, AlpenAalAlex commented on phobos/utils/misc.py
> +    proc = subprocess.Popen([cmd], stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True, cwd=cwd, executable="/bin/bash")
This does not work on Windows. For Windows the code can look like this:
proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True, cwd=cwd)
which changes
[cmd] -> cmd
executable can be omitted or usually C:\\Windows\system32\cmd.exe

2024-06-24 13:47 UTC, AlpenAalAlex commented on phobos/ci/base_model.py
> +                        readme.write(open(resources.get_resources_path("GitLFS_README.md.in")).read())
Faulty indentation

2024-07-03 09:03 UTC, hwiedPro commented on phobos/utils/misc.py
> +    proc = subprocess.Popen([cmd], stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True, cwd=cwd, executable="/bin/bash")
Ok thanks for the test. I'll put the executable as argument as it has a very specific use case.

2024-07-03 09:27 UTC, hwiedPro commented
Thanks for your review, I fixed the issues you have found.

2025-02-06 13:45 UTC, m0rsch1 commented
@hwiedPro @AlpenAalAlex i have some huge fixes regarding to SMURFA export, etc. Can i directly push into this branch (if given access to) or do i have to fork?

2026-05-14 16:28 UTC, brean commented
I think we can just take this, release it as 2.1.0 and build ontop of it for a new "3.0.0" release with the goal to support additional Blender versions.

2026-05-22 07:38 UTC, merged